# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: CONTENT_DIRECTORY
  value: app-directory
- name: NOW
  value: ${{date "+%Y-%m-%d %H:%M:%S"}}

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Bash@3
  inputs:
    filePath: 'create-upload-deploy.sh'
    arguments: 'Content Title - ${NOW}'